name: Build and Push MLOps Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ml/**'

jobs:
  # --- NOUVEAU JOB : TESTS UNITAIRES ---
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry==2.2.1

      - name: Install dependencies
        working-directory: ./ml
        run: poetry install --no-interaction

      - name: Run Pytest
        working-directory: ./ml
        # On exécute pytest dans le dossier /tests
        run: poetry run pytest tests/

  # --- TON JOB ACTUEL DE BUILD ---
  build:
    name: Build and Push Docker Image
    needs: test # CRÉCIAL : Ce job attend que le job "test" soit validé !
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./ml
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/helmet-model:${{ github.sha }}

      - name: Update GitOps Tag for Airflow
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}/mlops-framework:${{ github.sha }}" > dags/scripts/image_version.txt
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add dags/scripts/image_version.txt
          git commit -m "🤖 GitOps: Update Docker image tag to ${{ github.sha }}"
          git push